baseURL = 'https://julio77it.github.io/'
languageCode = 'en-us'
title = 'Sketchbook'
description = 'not a portfolio, just a sketchbook'
theme = "ananke"

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
